version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: nducanh210503
      MYSQL_DATABASE: maternal_child_health
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-mysql-net

  mch-back-end:
    container_name: mch-back-end
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - springboot-mysql-net
    restart: on-failure

networks:
  springboot-mysql-net:
    driver: bridge

volumes:
  mysql_data: